package com.example.airbookingapp.air_booking_app.data.mapper;

import com.example.airbookingapp.air_booking_app.data.request.FlightRequest;
import com.example.airbookingapp.air_booking_app.data.response.FlightResponse;
import com.example.airbookingapp.air_booking_app.jooq.tables.pojos.Flight;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring")
public interface FlightMapper {
    // Map FlightRequest to Flight (POJO)
    @Mapping(target = "id", ignore = true) // Generated by trigger, ignore during creation
    @Mapping(target = "flightId", ignore = true) // Generated by trigger, ignore during creation
    Flight fromRequestToPojo(FlightRequest flightRequest);

    // Map Flight (POJO) to FlightResponse
    FlightResponse fromPojoToResponse(Flight flight);

    // Update existing Flight POJO from FlightRequest
    @Mapping(target = "id", ignore = true) // Generated by trigger, ignore during update
    @Mapping(target = "flightId", ignore = true) // Generated by trigger, ignore during update
    void updateFromRequestToPojo(FlightRequest flightRequest, @MappingTarget Flight flight);
}
